### ISSUE TITLE
nothing happen when i change rest_enable_keys from FALSE tu TRUE

### ISSUE THREAD

**Issue by yuniargb** [chriskacerguis/codeigniter-restserver#1068]

**Comment by Rehman1994** [comment]
Facing the same issue:

rest.php:
`$config['rest_auth'] = 'basic';
$config['auth_library_class'] = '';
$config['auth_library_function'] = '';
$config['rest_enable_keys'] = TRUE;
$config['auth_source'] = 'ldap';
$config['rest_enable_logging'] = TRUE;
`
Every other configuration is default.

It comes inside the function `    protected function _prepare_basic_auth(){ ...`, but when i test the api in postman it does not require any authorization headers, it just allows the controller function to run.

Not sure if it is something on my end. I have followed a few tutorials and youtube videos but all seem to be doing the samething.

Any help would be appreciated.

**Comment by leanec** [comment]
Any news?

**Comment by Rehman1994** [comment]
@leanec turns out in my case i was using some different package and installation procedure. Its been quite some time so i can't quote which package was that but it was a copy of this package. 
All i did was deleted that package using composer installed this one and followed the instructions and it worked.
