### ISSUE TITLE
URI method repeats twice

### ISSUE THREAD

**Issue by petercpwong** [chriskacerguis/codeigniter-restserver#111]
Consider the following class

class Users extends REST_Controller{
  public function index_post($id){
  }
  public function subscription_post(){
    //do stuff here
  }
}

I can only only access the index method via http://myserver.com/users/users/1

The expected URL should be http://myserver.com/users/1/ (this gives a 404)

Is this a bug or am I doing something wrong?

**Comment by mahendravikhar** [comment]
Hi Phil

I am using the route for my purpose and getting proper response with the xml format which I define in my rest config. but as user request we also want to use the .json and .html for other format response and we are not getting that after using the route.

Please tell me what we need to update so that will works. please check my routes for more details.

$route['mainserver/(:any)'] = 'Mainserver/index/$1';
I have a controller with name Mainserver and my method is index_post and I am tacking 1 argument. My url is https://www.domain.com/mainserver/userdata now I want  to use https://www.domain.com/mainserver/userdata/json for response in json or https://www.domain.com/mainserver/userdata/html for response in html.

I am using extended route file in core folder to use advance routing via folder and other routing options.
