### ISSUE TITLE
Registration OTP verification using  AJAX with Codeigniter

### ISSUE THREAD

**Issue by bindsatyam** [chriskacerguis/codeigniter-restserver#1116]
**Describe the bug**

**To Reproduce**
Please provide either a cleanly formatted code snippet or a link to repo / gist with code that I can use to reproduce:

```php
    public function set_response($data = null, $http_code = null)
    {
        $this->response($data, $http_code, true);
    }
```

**Expected behavior**

**Screenshots / Error Messages**
If applicable, add screenshots and/or error messages to help explain your problem.

**Environment (please complete the following information):**
 - PHP Version: [e.g. 7.2.1]
 - CodeIgniter Version [e.g. 4.0.1]

**Additional context**

**Comment by chriskacerguis** [comment]
[canned response] I'm sorry, but you have not provided any information (or enough) as to what the issue is.  Please resubmit and provide all the information requested in the bug template.  I wish I would have time to dig into your issue deeper, if you would like that level of support please consider sponsoring this project.
