### ISSUE TITLE
$this->post('blah'); not retrieving anything

### ISSUE THREAD

**Issue by craigward** [chriskacerguis/codeigniter-restserver#214]
I'm not sure if this is the right place to post this but I am having an issue using this package. When I try to use $this->post('something'); it doesn't work. The only way I can retrieve information is by doing the following $postdata = json_decode(file_get_contents("php://input"), true);

Is there something I am missing?

**Comment by lunkadbhushan** [comment]
Hi, 
When I am using GET request, it's working fine. But when I am using POST request, I am getting an below error: 
{
  "status": false,
  "error": "Unknown method"
}

**Comment by cesardmoro** [comment]
I have the same issue, was working before on the same server and other projects

**Comment by Haseebfayyaz** [comment]
I am also facing same issue. I am testing on Postman. There is  some setting for header ?

**Comment by Haseebfayyaz** [comment]
on post request to check data I have run this in my conroller
var_dump($this->post());
var_dump(file_get_contents('php://input'));
I am receiving this on response how to solve this problem
array(0) {
}
string(244) "------WebKitFormBoundaryAIlR4w0r7Wb6gNK2
Content-Disposition: form-data; name="ofc_city"

islamabad
------WebKitFormBoundaryAIlR4w0r7Wb6gNK2

**Comment by ropali** [comment]
I am also facing this issue while sending the data as raw JSON in Postman like this,
![image](https://user-images.githubusercontent.com/31515245/67616184-5c599880-f7f3-11e9-8eba-2bc0cd8952b5.png)
The "Invalid request" message I am getting here because it can't find the value in the `$this->input->post('fcm_token')` & `$this->input->post('device_id')`
**But...**
If I send those values as `form-data` in Postman then it works perfectly fine. Take a look at the screenshot below in Postman
![image](https://user-images.githubusercontent.com/31515245/67616240-0cc79c80-f7f4-11e9-97a1-d31464063826.png)
I have confirmed this issue when I try to make the same request via my Flutter application. In my android app If I make the request with the body as JSON string then it shows the same error as in Postman with Raw JSON data settings.
But here also If I make my request as Multipart Form request then it works as same as in Postman with the form-data request settings.

**Comment by josecheogomez** [comment]
tengo el mismo problema @ropali , lograste solucionarlo?

**Comment by manikandanfsd** [comment]
> make
can give example of Multipart Form request

**Comment by manikandanfsd** [comment]
> I am also facing this issue while sending the data as raw JSON in Postman like this,
> ![image](https://user-images.githubusercontent.com/31515245/67616184-5c599880-f7f3-11e9-8eba-2bc0cd8952b5.png)
> The "Invalid request" message I am getting here because it can't find the value in the `$this->input->post('fcm_token')` & `$this->input->post('device_id')`
> **But...**
> If I send those values as `form-data` in Postman then it works perfectly fine. Take a look at the screenshot below in Postman
> ![image](https://user-images.githubusercontent.com/31515245/67616240-0cc79c80-f7f4-11e9-97a1-d31464063826.png)
> I have confirmed this issue when I try to make the same request via my Flutter application. In my android app If I make the request with the body as JSON string then it shows the same error as in Postman with Raw JSON data settings.
> But here also If I make my request as Multipart Form request then it works as same as in Postman with the form-data request settings.

can give example of Multipart Form request

**Comment by ropali** [comment]
> > I am also facing this issue while sending the data as raw JSON in Postman like this,
> > ![image](https://user-images.githubusercontent.com/31515245/67616184-5c599880-f7f3-11e9-8eba-2bc0cd8952b5.png)
> > The "Invalid request" message I am getting here because it can't find the value in the `$this->input->post('fcm_token')` & `$this->input->post('device_id')`
> > **But...**
> > If I send those values as `form-data` in Postman then it works perfectly fine. Take a look at the screenshot below in Postman
> > ![image](https://user-images.githubusercontent.com/31515245/67616240-0cc79c80-f7f4-11e9-97a1-d31464063826.png)
> > I have confirmed this issue when I try to make the same request via my Flutter application. In my android app If I make the request with the body as JSON string then it shows the same error as in Postman with Raw JSON data settings.
> > But here also If I make my request as Multipart Form request then it works as same as in Postman with the form-data request settings.
> 
> can give example of Multipart Form request
> 
> @ropali 
> 

My code is same I just send the data as formdata instead of raw JSON from postman and it works.
