### ISSUE TITLE
PUT Request - strange values

### ISSUE THREAD

**Issue by marcvthooft** [chriskacerguis/codeigniter-restserver#396]
Hi, first of GREAT Library! Thank you so much..

I've got a strange issue with the PUT request. When I do a
PUT /profiles/12
'like=profiles' 
(on postman for example)

and I var_dump($this->put()):
array(1) { ["------WebKitFormBoundaryftrlI2BtHtcfTLqw Content-Disposition:_form-data;_name"]=> string(64) ""like" profiles ------WebKitFormBoundaryftrlI2BtHtcfTLqw-- " }

On a POST it would be var_dump($this->post()):
array(1) { ["bike"]=> string(8) "bouncing" }

A lot cleaner..

I hope I made myself clear.

Can you solve this for me @chriskacerguis ?

**Comment by chriskacerguis** [comment]
Thanks!

With the var_dump ($this->put()) is that everything it is returning?

Can you take a screenshot of the PAW settings /config you are using?

**Comment by marcvthooft** [comment]
Thanks for fast reply. I'm sorry what are these PAW setting /config? And more importantly where can I find them?

I had these trouble on a remote Linux Server, just tested them at my localhost (via XAMPP on my new Macbook :) And got exactly the same Issue.. See screenshot below, 

all I do in these functions:
```
var_dump($this->post());
var_dump($this->get());
```
![screenshot 2015-02-06 11 11 44](https://cloud.githubusercontent.com/assets/3807959/6077742/3c0e5480-adf2-11e4-8091-f2d4849f1f50.png)

**Comment by marcvthooft** [comment]
In the code of your REST_Controller.php I see PHP has a standard for $_POST, not for $_PUT.. Maybe this is where the problem lies?
```
/**
     * Parse POST
     */
    protected function _parse_post()
    {
        $this->_post_args = $_POST;

        $this->request->format and $this->request->body = file_get_contents('php://input');
    }

    /**
     * Parse PUT
     */
    protected function _parse_put()
    {
        // It might be a HTTP body
        if ($this->request->format) {
            $this->request->body = file_get_contents('php://input');
        }

        // If no file type is provided, this is probably just arguments
        else {
            parse_str(file_get_contents('php://input'), $this->_put_args);
        }

    }
```

**Comment by darkwhispering** [comment]
Hi, thanks for an amazing library.

I seem to have encountered the same issue.

What I'm using:
- Using latest version of your RESTServer library (downloaded 2 days ago)
- CodeIgniter 3.0RC2
- Localhost (OS X 10.10 with default Apache and PHP)

Just like @marcvthooft I'm doing a PUT request with Postman to test my API locally.
PUT /api/account/create
'type=email' 

`var_dump($this->put())` result in the same styled data
```
array(1) {
  ["------WebKitFormBoundaryBEwfshKXTL3oj5DO
Content-Disposition:_form-data;_name"]=>
  string(64) ""type"

email
------WebKitFormBoundaryBEwfshKXTL3oj5DO--
"
}
```

If I do the same with CodeIgniters own function [using php://input stream](http://www.codeigniter.com/userguide3/libraries/input.html#using-the-php-input-stream)
`var_dump($this->input->input_stream())` returns empty
```
array(0) {
}
```

If I try to select the specific parameter/key like `var_dump($this->put('type'))` I get
```
bool(false)
```

and with CI `var_dump($this->input->input_stream('type))` I get
```
NULL
```

I don't know if the issue is in CI 3.0RC2 or the RESTServer library, but when I saw this thread I thought I start here.

**Comment by chriskacerguis** [comment]
Ultimately, the REST server is just retuning 

````
file_get_contents('php://input');
````

So, if it is not returning anything, it's either because something is up with the server OR CI3.0-RC2 is intercepting the php://input before it gets to the REST server.

Investigating.

**Comment by chriskacerguis** [comment]
So from all my tests everything is working fine.  The one thing that I do see that you are submitting form data, and generally that's proper rest design.

**Comment by darkwhispering** [comment]
You are right.

It works just fine if submitting as 'x-www-form-urlencoded' and when I did actual AJAX tests a few days later with javascript it works fine as well. (forgot to update here about that, sry)
