### ISSUE TITLE
Example API, POST showing ID as false, using AJAX

### ISSUE THREAD

**Issue by paulcanning** [chriskacerguis/codeigniter-restserver#405]
I am playing with the example controller from the repo.

When using AJAX to do a POST, with the ID as a GET variable, and the name and email as POST data, the ID is returned as false.

Code:

$.ajax({
    data: { name: 'Paul', email: 'myemail@gmail.com'},
    type: 'post',
    url: "http://localhost/api_test/index.php/api/example/user?id=1234"
}).done(function(result){
    console.log(result);
});

Output:

{"id":false,"name":"Paul","email":"myemail@gmail.com","message":"ADDED!"}

I also noticed that adding a format GET variable to the URL doesn't work.

**Comment by abudulwadoodu** [comment]
Hi,
just a comment (based on code defined in  'example/user'), not as solution.

1.POST method
$this->get() - method is used to access data from URL query string
                   - this returns empty array
[while i changed $this->get('id) to $_GET['id'], it returns id=1234]

2. GET method
change your code
type:'get'
id=1 or id=2 or id=3     //defined in  'example/user' for get method

Conclusion : 
while using POST request, it seems to have some bug in $this->get() method.

**Comment by darkwhispering** [comment]
This looks to be a limitation in the library, not a bug.

When a POST request is made to the rest server, the function that is parsing GET data is never executed. The rest server is only parsing the POST data.

In the `__construct()` function it loads the requests matching parser with
`$this->{'_parse_' . $this->request->method}();`
As you can see, it only loads the current request method used.

So for the moment you have to use either CI `$this->input->get()` or PHP native `$_GET`. I would recommend the former as it returns NULL if the item does not exist.

[Input Class - CodeIgniter](http://www.codeigniter.com/userguide3/libraries/input.html#accessing-form-data)

**Comment by softwarespot** [comment]
This is fairly easy to fix. GET is parsed in the constructor. Look for this line:

```
        // Set up the GET variables
        $this->_get_args = array_merge($this->_get_args, $this->uri->ruri_to_assoc());
```
Though granted query params are not parsed, which is what @paulcanning is using in the example above.

So the fix is to change the URL from:
http://localhost/api_test/index.php/api/example/user?id=1234 >> http://localhost/api_test/index.php/api/example/user/id/1234

Also the resource i.e. user should be plural (users)

Therefore I declare this is not a bug and perhaps a feature request, with parsing query params in the _parse_post() function.

**Comment by abudulwadoodu** [comment]
Hi,
I was newbie to REST service at the time of my first post.

As @softwarespot said, the correct url to call is
http://localhost/api_test/index.php/api/example/user/id/1234

which returns the id
Object {id: "3", name: "Scotty", email: "example3@example.com", message: "ADDED!"} 

// no other changes required

**Comment by softwarespot** [comment]
@abudulwadoodu I was new to this library only a couple of weeks ago. Do you think it makes logical sense to parse the query params for a POST request?

**Comment by abudulwadoodu** [comment]
Hi @softwarespot,

<strong>No</strong>, i guess - parsing query params for POST request is not logical.

Since POST request in a REST service is used to create a record, i guess there is no need of query params.

I guess, usually in a REST service query params will contain only primary key  and which is used to get/update a record.

I had used  <a href="http://www.yiiframework.com/doc-2.0/guide-rest-quick-start.html">yii2 rest service recently</a>, which will use only POST params to serve the request, though we can access query params by calling Yii::$app->request->get()

GET /users: list all users page by page;
GET /users/123: return the details of the user 123;
POST /users: create a new user;
PUT /users/123: update the user 123;
DELETE /users/123: delete the user 123;
...

**Comment by lagaisse** [comment]
Hello
I didn't see that post before.
I'm using POST to insert objects that depends on resources just like in these guidelines https://github.com/WhiteHouse/api-standards#post-magazinesidarticles but not in the query string 

I think query parameters should only be used to filter, so with GET

**Comment by softwarespot** [comment]
So basically no bug. This can be closed then.

**Comment by softwarespot** [comment]
Use this function if you need to parse the query params

```
    /**
     * Get the query parameters as an associative array
     *
     * @return array|NULL Query parameters as an associative array e.g. key => value; otherwise, NULL
     */
    public function get_query_params()
    {
        // Declare a variable that will hold the REQUEST_URI
        $request_uri = NULL;

        // If using the commandline version
        if (is_cli())
        {
            $args = $this->input->server('argv');
            unset($args[0]);

            // Combine the arguments using '/' as the delimiter
            $request_uri = '/' . implode('/', $args) . '/';

            // Set the following server variables (perhaps not required anymore?)
            $_SERVER['REQUEST_URI'] = $request_uri;
            $_SERVER['PATH_INFO'] = $request_uri;
            $_SERVER['QUERY_STRING'] = $request_uri;
        }
        else
        {
            $request_uri = $this->input->server('REQUEST_URI');
        }

        // Declare a variable that will hold the query parameters
        $query_params = NULL;

        // Parse the query parameters from the query string
        parse_str(parse_url($request_uri, PHP_URL_QUERY), $query_params);

        return empty($query_params) === FALSE ? $query_params : NULL;
    }
```
