### ISSUE TITLE
Codeigniter 3.0.0:  Undefined property: stdClass::$db and $this->response ?

### ISSUE THREAD

**Issue by netsurfaces** [chriskacerguis/codeigniter-restserver#429]
Hello! Codeigniter 3.0.0 is out now, I see the package states "CodeIgniter 2.1.0 to 3.0-dev". Are extra steps needed to bring it up to speed for version 3.0.0, are you working on an update? 

On a fresh install of CI 3.0.0 with the latest version of the Rest Server I get the error, when accessing /api/example/user/id/3:  

Message:  Undefined property: stdClass::$db
Filename: libraries/REST_Controller.php
Line Number: 1583

I am not sure why it is trying to log anything in the database, I have the settings to FALSE in the default config/rest.php

On top of that, the $this->response($user, 200); in my controller does not print anything in the browser. If I do print_r I see the details of my user 3 as expected. 

Thank you for the good work! Looking forward... anxious to convert my current project to CI 3.

**Comment by nguyenanhnhan** [comment]
The problem is not the CI 3. Which by an access code called db . To fix this , you can follow two ways :
- open config/autoload.php. Replace $autoload['libraries'] = array('') to **$autoload['libraries'] = array('database');**
- Or add **this->load->database();** on function _construct of REST_Controller.php.
Hope to help you.

**Comment by lalithsagar03** [comment]
Severity: Notice

Message: Undefined property: REST_Controller::$load

i got the following error can any one help me to resolve?
