### ISSUE TITLE
Need Unit Testing

### ISSUE THREAD

**Issue by chriskacerguis** [chriskacerguis/codeigniter-restserver#476]
Need to create unit testing using CI's Unit Testing framework (not ideal, but it's better than what we have).

**Comment by softwarespot** [comment]
Looking forward to this addition to the project

**Comment by abfan1127** [comment]
why would you not use PHPUnit?

**Comment by RodolfoSilva** [comment]
[This is stable library for PHPUnit tests](https://github.com/kenjis/ci-phpunit-test/).
https://github.com/kenjis/ci-phpunit-test/

But,  we'll need to change the `header` function for output library.

**Comment by kenjis** [comment]
Hi, I added how to test codeigniter-restserver controllers in  my ci-phpunit-test docs:
https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#codeigniter-rest-server

I have to say, to test codeigniter-restserver controllers is very difficult, because it calls `exit()` in `REST_Controller`.
I hope you remove `exit()`. Without exit() we could write tests for our controllers more easily, and you could write tests for `REST_Controller` easily, too.

**Comment by chriskacerguis** [comment]
Yeah, it's a pain for sure.  That's why I was planning on using the built in Unit Test class.  It's not super advanced, but it's easier to use in CI.

**Comment by softwarespot** [comment]
I ain't the sharpest tool in the draw, but the simple fix would be exit; => return; and the exit()s become exceptions. Am I right?

**Comment by kenjis** [comment]
@softwarespot 

Unfortunately the change (`exit;` => `return;`) is BC break:
https://github.com/softwarespot/codeigniter-restserver/commit/af4c8b77c7c62a1ae8f9d531f065fdf0c7270fb8#diff-7d748d7e419940392ec500f54eab66f2L756

Probably if you apply the change, almost all users must change their controller code.
Because code after `$this->response()` in controllers will run.
See https://github.com/chriskacerguis/codeigniter-restserver/blob/master/application/controllers/api/Example.php#L52 . There are lot of code after `$this->response()`.

**Comment by softwarespot** [comment]
I was a little too quick with updating.
