### ISSUE TITLE
Add support for HTTP verbs

### ISSUE THREAD

**Issue by RodolfoSilva** [chriskacerguis/codeigniter-restserver#496]
We need add suport for HTTP verbs.

http://www.codeigniter.com/user_guide/general/routing.html#using-http-verbs-in-routes

**Comment by softwarespot** [comment]
The library supports HTTP verbs. GET, POST, DELETE, PUT, PATCH, OPTIONS and HEAD to be exact. Could you elaborate your feature request please or maybe come up with some sample code. Thanks

**Comment by lagaisse** [comment]
What I understand is that with the http verbs support in CI3, we could deport the support of the http verb from the library to the core of the framework, i.e rewriting the `_detect_method()` method.

**Comment by chriskacerguis** [comment]
@softwarespot so based on my understanding of what I read, CI 3 supports http verbs in the routes file (awesome).  So I'm looking to rework the REST_Controller.php file and set it up as a library as CI 2 didn't support verbs, which is why we needed the REST_Controller and the _detect_method, etc.

That said...it's going to be a MAJOR rewrite of things (in a good way, I'll be able to do a lot of cleanup), but it will take some time.

**Comment by softwarespot** [comment]
OK, so if I am understanding correctly, this new library wouldn't be about mapping anymore, as that would be handled by using the routes file. The library would be about output, authorization etc... I knew about this enhancement, but I  guess I like the approach presented in the following controller.

**Comment by ivantcholakov** [comment]
Before a major rewrite it would be nice a minor release 2.7.2 to be done.

**Comment by softwarespot** [comment]
I agree, it would be a good idea
