### ISSUE TITLE
Form_Validation issue

### ISSUE THREAD

**Issue by hosseinsalemi** [chriskacerguis/codeigniter-restserver#586]
I'm using `form_validation` and write validation rules in `config/form_validation.php`. In validation rules I add some functions, for example trim() to trim input data.

    $this->form_validation->set_data( $this->post() );
    if ($this->form_validation->run() != FALSE)
    {
        // get input but not validated data :(
        $input = $this->post();
    }

but when call `$this->post()`, data didn't trim! How can I get validated data?

**Comment by fernandodeveloper** [comment]
try` $this->form_validation->set_value('name_input')`

**Comment by amitkm040** [comment]
my MY_Form_valiation.php
<?php

class MY_Form_validation extends CI_Form_validation {
  function __construct($rules = array()) {
   parent::__construct($rules);
   $this->ci =& get_instance();
  }

  public function get_errors_as_array() {
   return $this->_error_array;
  }

  public function get_config_rules() {
   return $this->_config_rules;
  }

  public function get_field_names($form) {
   $field_names = array();
   $rules = $this->get_config_rules();
   $rules = $rules[$form];
   foreach ($rules as $index => $info) {
    $field_names[] = $info['field'];
   }
   return $field_names;
  }
}

my form_validation.php

<?php if( ! defined('BASEPATH') ) exit('No direct script access allowed');


$config = array(

   'student_put' => array(
   array( 'field' => 'email_address', 'label' => 'email_address', 'rules' => 'trim|required|valid_email' ),
   array( 'field' => 'password', 'label' => 'password', 'rules' => 'trim|required|min_length[8]|max_length[16]' ),
   array( 'field' => 'first_name', 'label' => 'first_name', 'rules' => 'trim|required|max_length[50]' ),
   array( 'field' => 'last_name', 'label' => 'last_name', 'rules' => 'trim|required|max_length[50]' ),
   array( 'field' => 'phone_number', 'label' => 'phone_number', 'rules' => 'trim|required|alpha_dash' )
  )

);
?>﻿


my student_put function

function student_put(){
		$this->load->library('form_validation');		
		$this->form_validation->set_data($this->put()) ;
		if ($this->form_validation->run('student_put') != false){
			$this->load->model('Model_students');
			$student = $this->put();
			$student_id = $this->Model_students->insert($students);
			if (!$student_id) {
				$this->response(array('status'=>'failure','message'=>'An un-expected error occured while trying to insert student details'),REST_Controller::HTTP_INTERNAL_SERVER_ERROR);
			}
			 else {
			 	$this->response(array('status'=> 'success','message'=>'Student data successfully inserted'));
			 }
		}else {
			$this->response(array('status'=> 'failure','message'=>$this->form_validation->get_errors_as_array()), REST_Controller::HTTP_BAD_REQUEST);
		}
		
	}


I am getting this error even after filling all required filled 

{
    "status": "failure",
    "message": {
        "email_address": "The email_address field is required.",
        "password": "The password field is required.",
        "first_name": "The first_name field is required.",
        "last_name": "The last_name field is required.",
        "phone_number": "The phone_number field is required."
    }
}


Can anybody please help me out , Thanks in advance

**Comment by fernandodeveloper** [comment]
Check content put

Var_dump($this->put()) or print_r($this-put())

Send result of this.
Em 4 de mai de 2016 3:45 AM, "amitkm040" <notifications@github.com>
escreveu:

my MY_Form_valiation.php
<?php

class MY_Form_validation extends CI_Form_validation {
function __construct($rules = array()) {
parent::__construct($rules);
$this->ci =& get_instance();
}

public function get_errors_as_array() {
return $this->_error_array;
}

public function get_config_rules() {
return $this->_config_rules;
}

public function get_field_names($form) {
$field_names = array();
$rules = $this->get_config_rules();
$rules = $rules[$form];
foreach ($rules as $index => $info) {
$field_names[] = $info['field'];
}
return $field_names;
}
}

my form_validation.php

<?php if( ! defined('BASEPATH') ) exit('No direct script access allowed');

$config = array(

'student_put' => array(
array( 'field' => 'email_address', 'label' => 'email_address', 'rules' =>
'trim|required|valid_email' ),
array( 'field' => 'password', 'label' => 'password', 'rules' =>
'trim|required|min_length[8]|max_length[16]' ),
array( 'field' => 'first_name', 'label' => 'first_name', 'rules' =>
'trim|required|max_length[50]' ),
array( 'field' => 'last_name', 'label' => 'last_name', 'rules' =>
'trim|required|max_length[50]' ),
array( 'field' => 'phone_number', 'label' => 'phone_number', 'rules' =>
'trim|required|alpha_dash' )
)

);
?>﻿

my student_put function

function student_put(){
$this->load->library('form_validation');

$this->form_validation->set_data($this->put()) ;
if ($this->form_validation->run('student_put') != false){
$this->load->model('Model_students');
$student = $this->put();
$student_id = $this->Model_students->insert($students);
if (!$student_id) {
$this->response(array('status'=>'failure','message'=>'An un-expected error
occured while trying to insert student
details'),REST_Controller::HTTP_INTERNAL_SERVER_ERROR);
}
else {
$this->response(array('status'=> 'success','message'=>'Student data
successfully inserted'));
}
}else {
$this->response(array('status'=>
'failure','message'=>$this->form_validation->get_errors_as_array()),
REST_Controller::HTTP_BAD_REQUEST);
}

}

I am getting this error even after filling all required filled

{
"status": "failure",
"message": {
"email_address": "The email_address field is required.",
"password": "The password field is required.",
"first_name": "The first_name field is required.",
"last_name": "The last_name field is required.",
"phone_number": "The phone_number field is required."
}
}

Can anybody please help me out , Thanks in advance

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/chriskacerguis/codeigniter-restserver/issues/586#issuecomment-216759542>

**Comment by hosseinsalemi** [comment]
Thanks a lot.
