### ISSUE TITLE
CI_Format not found

### ISSUE THREAD

**Issue by ecowed** [chriskacerguis/codeigniter-restserver#589]
Fatal error: Class 'CI_Format' not found in /path-to-install/system/core/Common.php on line 196

I know this has been discussed before and it was resolved by redownloading and starting again which I have done and still no joy. 

I have downloaded the latest stable version of CI and the CI-restserver files.

Attached is my rest.php (currently has a .png extension) config file which is the only file I have made any changes to - in summary, I have set auth_type to digest, source to library and set the library up (currently just returns TRUE); 

Any suggestions gratefully received! 
![rest](https://cloud.githubusercontent.com/assets/15327493/11533424/833b4b1a-9901-11e5-85fe-97c6629f5c2f.png)

**Comment by chriskacerguis** [comment]
Seems like a CI problem to me.  (also nothing attached).

**Comment by vatsalgor** [comment]
I have similar problem @ecowed  @chriskacerguis 
![image](https://cloud.githubusercontent.com/assets/11296272/18816262/3bc9b666-8363-11e6-91cb-c831f2667a06.png)

**Comment by pieterlourens** [comment]
Well like most PHP errors it's telling you where the issue is:
`Fatal error: Class 'CI_Format' not found in [install path]/system/core/Common.php on line 196`

If you go to that line you'll see it's a parameterless class instantiation that's failing.  Furthermore, you'll see in Common.php on line 159 where 'CI_' is getting prepended to the classname, hence not finding it as the Class is called 'Format', not 'CI_Format'.  This behaviour fine for Codeigniter core classes, but not for custom ones like the Class in question.

So, the dirty little workaround that worked for me was adding the following :
`if ($name == 'CI_Format') {
      $name = 'Format';
  }` 
to line 194, just before the class gets instantiated, so the correct class name is used for instantiation.

Use it, don't use it, but I hope it helps someone else.
