### ISSUE TITLE
CSV and HTML format return empty values on valid query result

### ISSUE THREAD

**Issue by efCode** [chriskacerguis/codeigniter-restserver#687]
I have a set of db queries which get returned in the API GET method. It formats correctly in each specified format except HTML and CSV.

For example the html format returns the following :

<table border="0" cellpadding="4" cellspacing="0">
<thead>
<tr>
<th>0</th><th>1</th><th>2</th><th>3</th><th>4</th><th>5</th><th>6</th><th>7</th><th>8</th><th>9</th><th>10</th><th>11</th><th>12</th><th>13</th><th>14</th><th>15</th></tr>
</thead>
<tbody>
<tr>
<td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
</tbody>
</table>

I am using codeigniters last version.

Is this an issue on my side ?

**Comment by chriskacerguis** [comment]
I really can't tell you the issue, you haven't provided enough info.  Ultimately thought, we are using the CI html / csv generators.

**Comment by nicolaib** [comment]
I have the same issue and just realized that the output render exactly as you describe, if you send a collection (like a database result) to the response method. If you convert the collection to have nested arrays instead of objects, then the output is correct for HTML and CSV. The library should probably be able to handle a collection, but to fix it in your output it is not harder than casting to arrays like this:
```
$response = array();
foreach($items as $item){
    $response[] = (array)$item;
}
```
Because the library can't handle this currently, the format=CSV or format=HTML URL parameters seems to be not usable without an internal condition to check for those output types.
I hope this helps someone and I also suggest for it to be fixed :-)
