### ISSUE TITLE
Request being empty when changing Subclass Prefix

### ISSUE THREAD

**Issue by cesardmoro** [chriskacerguis/codeigniter-restserver#791]
Hi guys

This issue is related to this one:
https://github.com/chriskacerguis/codeigniter-restserver/issues/214

When you change:
`$config['subclass_prefix'] = 'MY_';`
for another prefix The request $this->post() and $this->put() become empty so you have to do:
$postdata = json_decode(file_get_contents("php://input"), true);

Im forking right now to see if i can fix it, but maybe someone knows why this happens.

**Comment by chriskacerguis** [comment]
Hmmm...we just use the CI info for that.  Thinking maybe there might be something in the CI code itself (b/c it sounds like it's working with the MY_)

**Comment by cesardmoro** [comment]
Why u just instaclose the issue ? With MY_ it works, but i dont want to use it like that, it is a bug you just want to ignore it.

**Comment by mdeuerlein** [comment]
The "Problem" has got nothing to do with the Subclass Prefix. You get an empty Request if you  send the Request-Data within the body which is not supported. 

By changing the Subclass Prefix to "MY_" you just use some kind of codeigniter "workaround" because `php://input" === $this->input->raw_input_stream` in codeigniter when called from a controller that extends CI_Controller and MY_Controller usually extends CI_Controller.

For more details check #113

**Comment by Haseebfayyaz** [comment]
I am trying post form but in post therei sno data how I should solve this problem ??
var_dump($this->post());
var_dump(file_get_contents('php://input'));
Result:
array(0) {
}
string(244) "------WebKitFormBoundaryoyapysELiKZBwUtV
Content-Disposition: form-data; name="ofc_city"
