### ISSUE TITLE
how to start ?

### ISSUE THREAD

**Issue by AbolfazlDalily** [chriskacerguis/codeigniter-restserver#936]
When I run the composer require chriskacerguis/codeigniter-restserver command, the codeigniter framework and the project was downloaded to the vendor folder.
I do not know how to get started

**Comment by programetica** [comment]
@alexhobday  I think that the project owner put the CodeIgnier system files in the vendor folder due to the CI recommendation to remove those files from the application root (I think they're supposed to go outside somewhere) for security purposes?

Thanks for your corrections and modifications to make it simpler, I'm looking at them too.
