### ISSUE TITLE
authenticate the client user with keys as token

### ISSUE THREAD

**Issue by sepisoltani** [chriskacerguis/codeigniter-restserver#941]
Hi , I created the table "Keys" in my DB and then I enabled "rest_enable_key" config in the rest.php file of my project . then I added 1 key in my "Keys" table and then send that in the request header and get the response very well . in this format : x-api-key = key ;
the issue is that I need to generate different keys from calling a special url in order to bring it forward to my users as a token to authenticate them . but when I use Key Controller in the library to generate it response that {invalid api key} . why it needs api key to generate new key ? how can I make different keys with the rest api get method?

**Comment by codeamancoder** [comment]
Hello @sepisoltani, if you want to add this feature into your app, you may take a look JWT instead of its own secure key approach. a simple endpoint such as "/auth" will create a token at first request when they sent correct credentials like any public key provided by you ex: any variations of x-api-keys can be.. and you will respond to user generated JWT .They will use this token for the next requests as "Autharizarion: Bearer _JWT key_" in request header untill expired. They have to regenerate when it expired as well

**Comment by chriskacerguis** [comment]
FWIW - I'm not opposed to adding something like this in the lib...PR's are always welcome.  I'll flag this as "Help Wanted" for the time being.
