### ISSUE TITLE
If method don't exists please don't execute index_{request_method}

### ISSUE THREAD

**Issue by Seraph11** [chriskacerguis/codeigniter-restserver#954]
I don't understand why execute this
https://github.com/chriskacerguis/codeigniter-restserver/blob/de75ca9157cd48b3ceb266a1ae4e3d1dfe3ff40f/application/libraries/REST_Controller.php#L688

if method don't exist just call the response with code HTTP_METHOD_NOT_ALLOWED, like 
https://github.com/chriskacerguis/codeigniter-restserver/blob/de75ca9157cd48b3ceb266a1ae4e3d1dfe3ff40f/application/libraries/REST_Controller.php#L737

Sorry if I sound rude, English is not my primary language.

**Comment by chriskacerguis** [comment]
I don't think you are sounding rude :)

BUT, I'm not following your issue.  Could you please clarify?

**Comment by Seraph11** [comment]
Hi Chris, for example if I have a endpoint:
```
POST myapi.com/user/update
```
And try to access 
```
GET myapi.com/user/update
```
The library verify if the method update_get exists (which is false), so the library immediately assign the request to the method index_get, if index_get exists the API show the result of index_get and no the response error whit code HTTP_METHOD_NOT_ALLOWED.

**Comment by imrohan22** [comment]
Solved this issue. @chriskacerguis 
It was because - Default method call is set when no method found.
change at line no.: 67 

`$controller_method = $object_called.'_'.$this->request->method;`
https://github.com/chriskacerguis/codeigniter-restserver/blob/d51e373ff151e3b7ed1aefbb6addb40fcedfaf17/application/libraries/REST_Controller.php#L687

to

`$controller_method = $object_called;`

It will work. :)
